OnlineSurvey/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from survey.views import Signup, Login, Logout
from rest_framework.routers import DefaultRouter
urlpatterns = [
   url(r'^admin/', admin.site.urls),
   url(r'^user/', include('survey.urls', namespace='user')),  
   url(r'^$', TemplateView.as_view(template_name="survey/login.html")),
   url(r'^signup/$', TemplateView.as_view(template_name="survey/signup.html")),
   url(r'^dashboard/$', TemplateView.as_view(template_name="survey/dashboard.html")),
   url(r'^show-list/$', TemplateView.as_view(template_name="survey/ShowSurvey.html")),
   url(r'^survey/(?P<survey_id>[0-9]+)/$',TemplateView.as_view(template_name="survey/Design.html")),
   
]

survey/urls.py
from survey.views import Signup, Login, Logout ,SurveyForm,SurveyDesign
from rest_framework.routers import DefaultRouter
from survey import views
from django.conf.urls import url

router = DefaultRouter()

app_name = 'survey'
router.register(r'signup', Signup, base_name='signup'),
router.register(r'login', Login, base_name='login'),
router.register(r'logout', Logout, base_name='logout'),
router.register(r'save-survey-form',SurveyForm,base_name='save_survey_form')
router.register(r'list',SurveyForm,base_name='list')

router.register(r'Survey-Design',SurveyDesign,base_name='Survey_Design')




urlpatterns = router.urls

survey/models.py
from django.contrib.auth.models import User, Group
from django.db import models

# Create your models here.
class ClientSurvey(models.Model):
    user = models.ForeignKey(User, related_name="user_name",on_delete=models.CASCADE)
    name = models.CharField(max_length=100,)
    description = models.TextField(max_length=3000,null=True,blank=True)

class SurveyDesingForm(models.Model):
    survey = models.ForeignKey(ClientSurvey, related_name="survey_name",on_delete=models.CASCADE)
    lebel_data = models.CharField(max_length=100,null=True,blank=True)
    level_x = models.CharField(max_length=100,null=True,blank=True)
    level_y = models.CharField(max_length=100,null=True,blank=True)

    value = models.CharField(max_length=100,null=True,blank=True)
    value_x = models.CharField(max_length=100,null=True,blank=True)
    value_y = models.CharField(max_length=100,null=True,blank=True)

survey/forms.py
from django import forms

from .models import ClientSurvey

class ClientSurveyForm(forms.ModelForm):

    class Meta:
        model = ClientSurvey
        fields = "__all__"

survey/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from django.utils.decorators import method_decorator
from rest_framework import mixins
from rest_framework import status
from rest_framework import viewsets
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.authtoken.models import Token
from rest_framework.viewsets import ModelViewSet
from rest_framework.permissions import IsAuthenticated, AllowAny, IsAuthenticatedOrReadOnly
from .models import ClientSurvey,SurveyDesingForm
from .serializers import (SignupSerializer, LoginSerializer, LogoutSerializer, ClientSurveySerializer,
                          AllSurveySerializer,SurveyFormSerializer,AllSurveyFormSerializer)
from django.shortcuts import get_object_or_404
import json

###################################################################################
#                    Survey Design Form API VIEW                                  #
###################################################################################
class SurveyDesign(viewsets.ViewSet):
    serializers_class=SurveyFormSerializer
    models = SurveyDesingForm
    permission_classes = (IsAuthenticatedOrReadOnly,)
    def create(self,request):
        store_list = request.POST['jsonformate']
        print(store_list)
        design_data = json.loads(store_list)
        print(design_data[0])
        for data in design_data:
            serializer = self.serializers_class(data=data)
            if serializer.is_valid(raise_exception=True):
                survey_id=ClientSurvey.objects.get(id=data['survey'])
                SurveyDesingForm.objects.create(survey= survey_id,
                                                lebel_data= data['lebel_data'],
                                                level_x= data['level_x'], 
                                                level_y= data['level_y'],
                                                value= data['value'], 
                                                value_x= data['value_x'],
                                                value_y= data['value_y'])
        return Response({
           "status": '200',
           "success" : True,
           "message" : "Successfully Data Saved",
          } )

    def list(self,request):
        # import pdb; pdb.set_trace()
        # surveys=SurveyDesingForm.objects.filter(survey=request.GET['id'])
        surveys=SurveyDesingForm.objects.all() 
        serializer = AllSurveyFormSerializer(surveys, many=True)
        return Response(serializer.data)

    def retrieve(self,request,pk):
        queryset = SurveyDesingForm.objects.filter(survey=pk)
        serializer = AllSurveyFormSerializer(queryset,many=True)
        return Response(serializer.data)

###################################################################################
#                    Survey Form API view                                         #
###################################################################################

class SurveyForm(viewsets.ViewSet):
    serializers_class= ClientSurveySerializer
    model = ClientSurvey
    permission_classes = (IsAuthenticatedOrReadOnly,)

    def create(self, request):
        serializer = self.serializers_class(data=request.data)
        if serializer.is_valid(raise_exception=True):
            name=request.POST['name']
            description=request.POST['description']
            user=request.user
            ClientSurvey.objects.create(name=name,description=description,user=user)
            return Response({
               "status": '200',
               "success" : True,
               "message" : "Successfully Data Saved",
              } )
  
    def retrieve(self,request,pk):
        queryset = ClientSurvey.objects.all()
        user = get_object_or_404(queryset, pk=pk)
        serializer = AllSurveySerializer(user)
        return Response(serializer.data)

    def list(self,request):
        surveys=ClientSurvey.objects.filter(user=request.user)
        serializer = AllSurveySerializer(surveys, many=True)
        return Response(serializer.data)

    def update(self, request, pk):
        instance=ClientSurvey.objects.get(id=pk)
        serializer =AllSurveySerializer(instance, data=request.data, partial=True)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response({"status": '200',
                          "success" : True,
                          "message" : "Successfully Updated",
                          })

    def partial_update(self, request, pk):
        instance=ClientSurvey.objects.get(id=pk)
        serializer =ClientSurveySerializer(instance, data=request.data, partial=True)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response({"status": '200',
                          "success" : True,
                          "message" : "Successfully Updated",
                          })

    def destroy(self, request, pk):
        instance=ClientSurvey.objects.get(id=pk)
        instance.delete()
        return Response({"status": '200',
                          "success" : True,
                          "message" : "Successfully Deleted",
                          })

###################################################################################
#                    User login/logout syste                                      #
###################################################################################

class Signup(viewsets.ViewSet):

    permission_classes = (AllowAny,)
    serializer_class = SignupSerializer
    model = Token  

    def create(self, request):
        serializer = self.serializer_class(data = request.data)
        if serializer.is_valid(raise_exception=True):
            user = serializer.save()
            username = user.username
            raw_password = user.password
            #again set password in HASH format
            user.set_password(raw_password)
            user.save()
            user = authenticate(username=username, password=raw_password)
            token, created = self.model.objects.get_or_create(user=user) 
            headers = { 'access_token': token.key }
            return Response({
                    "status": status.HTTP_201_CREATED,
                    "success" : True,
                    "message" : "Successfully Created Your Account.",
                    }, headers= headers )
        return Response(serializer.errors)


class Login(viewsets.ViewSet):

    permission_classes = (AllowAny,)
    serializer_class = LoginSerializer
    model = Token  
     
    def create(self, request):
        serializer = LoginSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        user = serializer.validated_data['user']
        try:
            token, created = self.model.objects.get_or_create(user=user)
        except Exception as e:
            pass  
        headers = { 'access_token' : token.key }
        return Response({
                    "status": status.HTTP_200_OK,
                    "message" : 'Successfully login.'
                    }, headers=headers)

class Logout(viewsets.ViewSet):  

    permission_classes = (AllowAny,)
    serializer_class = LogoutSerializer

    def create(self, request):
        serializer = self.serializer_class(data = request.data)
        serializer.is_valid(raise_exception=True)
        token = serializer.validated_data['token']
        if token:
            token.delete()
        else:
            pass
        return Response({
                    "status": status.HTTP_200_OK,
                    "message" : 'Successfully logout.'
                    })

templates/survey/Design.html
{% extends 'survey/base.html' %}
{% load static %}
{% block title %} Design Survey Page {% endblock %}
{% block stylesheet %} 
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'survey/css/Design.css' %}" />

 
{% endblock %}

{% block content %}
<div id="delete-drop">
Drag here to delete.
</div>

<!-- drop data -->
<input type="submit" class="form-control save_form" id="submit" value="Submit">
<div class="col-sm-6 data " style="" >
  <div id='Drop'>
  </div>      
</div>
<!-- here imput box to edit data -->
<div class='hide edit_level col-sm-2 '>
    <input type="text" class="form-control" id="lavel_name_value" value="">
    <button id='save_data' onclick="SaveData()">save-name</button>
</div>
<!-- drag able deiv -->
<div class="col-sm-6 start-drag" style="background-color:lavender;">

<div class="draggable">
    <p id='lebel'>Enter Level Name </p>
</div>
<div class="draggable">
  <div class="form-group">
  <input type="text" class="form-control" id="input" placeholder="Imput your data">
</div></div>
</div>
{% endblock %}
{% block javascript %}
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
<script src="{% static 'survey/js/Design.js' %}"></script>
{% endblock %}

templates/survey/ShowSurvey.html
{% load staticfiles %}
{% load static %}
{% load i18n %}
{% block stylesheet %} 
  <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">  -->
  <!-- thid code used to create background and my code inbult-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link href="{% static 'survey/css/style2.css' %}" rel="stylesheet" type="text/css">

<link rel="shortcut icon" href="{%  static 'survey/images/favicon.ico' %}">
<link rel="stylesheet" type="text/css" href="{% static 'survey/css/bootstrap.min.css' %}" />

{% endblock %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
  <title>show all data</title>
</head>
<body class="container">
<div >
  <div class="sky">
    <div class="stars"></div>
    <div class="stars1"></div>
    <div class="stars2"></div>
    <div class="shooting-stars"></div>
<div class="Start_Body"></div>
  <div id='Div_header'>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <ul class="nav navbar-nav">
      <li><a id="btnExport" ></a></li>   
    </ul>
    <form class="navbar-form navbar-right">
      <div class="input-group">
        <input type="text" class="form-control" id="search" placeholder="Search" onkeyup="myFunction()">
        <div class="input-group-btn">
          </button>
        </div>
      </div>
    </form>
  </div>
</nav>
</div>
<!-- ____________Div Menu Start Main Page______________________________________ -->
<div id='Table_back_div'>
<!-- _____________________TAble Start Here____________________________________ -->
<div id='table_wrapper'>
<table  class="results table table-hover " id='table_id'>
  <p class='pre'> <thead>
    <tr>
      <th class='id'>Id</th>

      <th class='name-'>Name </th>
      <th class='description'>Description </th>
      <th class='td7'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Action&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
    </tr>
  </thead></p>
  <tbody>    
  </tbody>
</table>
</div>
  
</div>
  </div>
</div>
</body>
{% endblock %}
{% block javascript %}<script>

//searching data
 $(document).ready(function(){  
           $('#search').keyup(function(){  
               var value = search_table($(this).val()); 
           });  
           function search_table(value){  
                $('#table_id tbody tr').each(function(){  
                     var found = 'false';  
                     $(this).each(function(){  
                          if($(this).text().toLowerCase().indexOf(value.toLowerCase()) >= 0)  
                          {  
                              found = 'true';  
                          }  
                     });  
                     if(found == 'true')  
                         {  
                               $(this).show();  
                         }  
                            else  
                             {  
                               $(this).hide();  
                             }  
                });  
           }  
      });  
</script>
<script src="{% static 'survey/js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'survey/js/get_all_survey.js' %}"></script>

{% endblock %}



  

templates/survey/base.html
 {% load static %}
 <!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}    Survey Portal  {% endblock %}</title>
    <link rel="shortcut icon" href="{%  static 'survey/images/favicon.ico' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'survey/css/bootstrap.min.css' %}" />
    <link href="{% static 'plugins/sweetalert.min.css' %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'survey/css/base.css' %}" />

    {% block stylesheet %}  
    {% endblock %}
</style>
</head>
<body>
<header>
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <button data-target="#header-menu" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse" id="header-menu">
          <a href="/" title='Logout' class="logout-btn btn btn-default navbar-btn navbar-right">  Logout   </a>         
          <a href="/" title="Sign in" class="signin-btn btn btn-default navbar-btn navbar-right">Sign in</a>           
          <a href="/signup/" title="Sign up" class="signup-btn btn btn-primary navbar-btn navbar-right" style="margin-right:5px;">
              Sign up </a>
      </div>     
    </div>   
  </nav>
</header> 
<div id='content'> 
 
  <script src="{% static 'survey/js/jquery.min.js' %}"></script>
  <script src="{% static 'survey/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'survey/js/logout.js' %}"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/0.5.0/sweet-alert.min.js"></script>
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/0.5.0/sweet-alert.css"/>

  {% block content %} {% endblock %} 
</div>


<script>
let token = localStorage.access_token
if (token){
$('.signup-btn').css('display' , 'none');      
$('.signin-btn').css('display' , 'none');      
$('.logout-btn').css('display' , 'inline');
}
else{
$('.signup-btn').css('display' , 'inline');      
$('.signin-btn').css('display' , 'inline');      
$('.logout-btn').css('display' , 'none'); 
}      
</script>
    {% block javascript %} {% endblock %}
<nav class="footer navbar-fixed-bottom navbar-default">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 legal">
                <br>
                <center> <span>© 2017 Survey Portal</span> </center>
                <br>
            </div>
        </div>
    </div>
</nav>
</body>
</html>

templates/survey/dashboard.html
{% extends 'survey/base.html' %}

{% load static %}

{% block title %} DashBoard {% endblock %}


{% block stylesheet %} 
  <link rel="stylesheet" type="text/css" href="{% static 'survey/css/dashboard.css' %}" />

{% endblock %}

{% block content %}


{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<div class='row'>
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default">
      <div class="panel-heading">
       <center> <h3 class="panel-title">Dashboard Data</h3> </center>
      </div>
      <div class="panel-body">
      <center id="get_url_link" data-get_url="/user/pet/"> 
        <div id= "nodata">
        </div>
      </center>
        <br>
        <div id="midpart" class="form-group text-center col-md-4">
        <!--  -->
           <form id='surveyform' action ="."  method='POST' >
          {% csrf_token %}
    
          <div class="panel-group">
              <label class="control-label" for="email"> name </label>
              <input type="text" class="form-control"  id="id_name" name="name" required>
              </div>

          <div class="panel-group">
              <label class="control-label" for="description"> Description</label>
              <textarea rows="4" cols="50" class="form-control"  id="id_description" name="description"></textarea>
            </div>
          <input type='submit' name='submit'>
          </form>
<!--  -->
        </div>

      </div>
    </div>
  </div>
</div> 
{% endblock %}
{% block javascript %}
  
<script>
function openNav() {
    document.getElementById("myNav").style.width = "100%";
}
function closeNav() {
    document.getElementById("myNav").style.width = "0%";
}
</script>
<script type="text/javascript" src="{% static 'survey/js/survey.js' %}"></script>
{% endblock %}

templates/survey/login.html
{% extends 'survey/base.html' %}

{% load static %}

{% block title %} login {% endblock %}


{% block content %}


{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}


<div class='row'>
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Login </h3>
      </div>
      <div class="panel-body">


          <form id='login_form' action ="." data-url="/user/login/"  method='POST' >
          {{ form.errors }}
          {% csrf_token %}
    
          <div class="panel-group">
              <label class="control-label" for="email"> Email </label>
              <input type="email" class="form-control"  id="id_email" name="email" required>
              </div>

          <div class="panel-group">
              <label class="control-label" for="id_password"> Password </label>
              <input type="password" class="form-control"  id="id_password" name="password" required>
            </div>

         <!-- <button type="submit" class="btn btn-success"  onclick="return Validate()" >Submit</button> -->
          <input type='submit' name='submit'>
          </form>



      </div>
    </div>
  </div>
</div>



  
{% endblock %}




  


{% block javascript %}
  
<script type="text/javascript" src="{% static 'survey/js/login.js' %}"></script>





{% endblock %}

templates/survey/signup.html
{% extends 'survey/base.html' %}

{% load static %}


{% block title %} SignUp {% endblock %}


{% block content %}

  {% if messages %}
  <ul class="messages">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>
  {% endif %}

  <div class='row'>
    <div class="col-md-6 col-md-offset-3">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"> Signup</h3>
        </div>
        <div class="panel-body">

 <form id='signup_form' action ="." data-url="/user/signup/"  method='POST' >
          {{ form.errors }}
          {% csrf_token %}

                <div class="panel-group">
                    <label class="control-label" for="username"> User Name </label>
                    <input type="text" class="form-control"  id="usesrname" name="username" required>
                    </div>

    
                <div class="panel-group">
                    <label class="control-label" for="email"> Email </label>
                    <input type="email" class="form-control"  id="id_email" name="email" required>
                    </div>

                <div class="panel-group">
                    <label class="control-label" for="id_password"> Password </label>
                    <input type="password" class="form-control"  id="id_password" name="password" required>
                </div>

                <div class="panel-group">
                  <label class="control-label" for="confirm-pass"> Confirm Password </label>
                  <input type="password" class="form-control" id="confirm-pass" name="confirm-pass" required>
                  <div id='gen_error'>                </div>

         <button type="submit" name='submit' class="btn btn-success"  onclick="return Validate()" >Submit</button>
          </form>


        </div>
      </div>
    </div>
  </div>



{% endblock %}




{% block javascript %}

  <script type="text/javascript" src="{% static 'survey/js/signup.js' %}"></script>

{% endblock %}